#baseurl = "https://datalaria.netlify.com/"
baseurl = "https://datalaria.github.io/"
#baseurl = "http://localhost:1313"
DefaultContentLanguage = "es"
#title = ""
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "datalaria"
#googleAnalytics = "XXX"

# [staticman]
#    api= "https://api.staticman.net/v2/entry/datalaria/datalaria.github.io/master/comments"
#    pulls= "https://github.com/datalaria/datalaria.github.io/pulls"
#    [recaptcha]
#      sitekey= "6LeGeTgUAAAAAAqVrfTwox1kJQFdWl-mLzKasV0v"
#      secret= "hsGjWtWHR4HK4pT7cUsWTArJdZDxxE2pkdg/ArwCguqYQrhuubjj3RS9C5qa8xu4cx/Y9EwHwAMEeXPCZbLR9eW1K9LshissvNcYFfC/b8KKb4deH4V1+oqJEk/JcoK6jp6Rr2nZV4rjDP9M7nunC3WR5UGwMIYb8kKhur9pAic="

[languages]
  [languages.es]
  homeTitle = "Datalaria" # Set a different text for the header on the home page
  title = ""
  weight = 1
  LanguageName = "ES"

  [languages.es.params.staticman]
     api= "https://api.staticman.net/v2/entry/datalaria/blog/master/comments"
     pulls= "https://github.com/datalaria/blog/pulls"
     [languages.es.params.staticman.recaptcha]
        sitekey= "6LcMllYUAAAAAM3XdBl7QWwLjXy_o_wZc6WmYZNu"
        secret= "tDXhHifxJgciHgyUt+LyAJkb9PTVXa5Vr+j6qHv8T1E9yyB/NINrwQZzeqKYfSs7a3Tb7yqfUGKtb2ZsG9gGW4QWpCQtzJ4SaEYLoiE7cXVf9LBz9YUTVcDcnkjwbJbpIzRPZNOSm6ovHl7zhBkQVuHTEGBauY8JfVY2HlZP5c8="

  [languages.es.params]
    subtitle = "Aprendiendo con los datos"
    logo = "img/datalaria-logo.png"
    favicon = "img/datalaria-icon.ico"
    dateFormat = "02-01-2006"
    commit = false
    rss = true
    comments = true
    readingTime = true
    useHLJS = true
    socialShare = true
    #etiquetas = "Etiquetas"

  [[languages.es.menu.main]]
      name = "Blog"
      url = ""
      weight = 1

  [[languages.es.menu.main]]
      identifier = "categorias"
      name = "Categorias"
      url = "categorias"
      weight = 2

  [[languages.es.menu.main]]
      parent = "categorias"
      name = "Fundamentos"
      url = "categories/fundamentos"
      weight = 1

  [[languages.es.menu.main]]
      parent = "categorias"
      name = "Proyectos"
      url = "categories/proyectos"
      weight = 2

  [[languages.es.menu.main]]
      parent = "categorias"
      name = "Casos de Éxito"
      url = "categories/casos_exito"
      weight = 3

  [[languages.es.menu.main]]
      parent = "categorias"
      name = "Utilidades"
      url = "categories/utilidades"
      weight = 4

  [[languages.es.menu.main]]
      name = "Etiquetas"
      url = "tags"
      weight = 3

  [[languages.es.menu.main]]
      name = "Contacto"
      url = "page/contact/"
      weight = 4

  [[languages.es.menu.main]]
      name = "Sobre mí"
      url = "page/about/"
      weight = 5
  #[[languages.es.taxonomies]]
      #tag = "etiquetas"
      #category = "categorias"


[languages.en]
homeTitle = "Datalaria" # Set a different text for the header on the home page
title = ""
weight = 2
LanguageName = "EN"

#[[languages.en.taxonomies]]
    #tag = "tags"
    #category = "categories"
[languages.en.params.staticman]
   api= "https://api.staticman.net/v2/entry/datalaria/blog/master/comments"
   pulls= "https://github.com/datalaria/blog/pulls"
   [languages.en.params.recaptcha]
   sitekey= "6LcMllYUAAAAAM3XdBl7QWwLjXy_o_wZc6WmYZNu"
   secret= "tDXhHifxJgciHgyUt+LyAJkb9PTVXa5Vr+j6qHv8T1E9yyB/NINrwQZzeqKYfSs7a3Tb7yqfUGKtb2ZsG9gGW4QWpCQtzJ4SaEYLoiE7cXVf9LBz9YUTVcDcnkjwbJbpIzRPZNOSm6ovHl7zhBkQVuHTEGBauY8JfVY2HlZP5c8="

[languages.en.params]
  subtitle = "Learning with data"
  logo = "img/datalaria-logo.png"
  favicon = "img/datalaria-icon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
  #etiquetas = "Tags"

[[languages.en.menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[languages.en.menu.main]]
    identifier = "categories"
    name = "Categories"
    weight = 2

[[languages.en.menu.main]]
    parent = "categories"
    name = "Foundations"
    url = "categories/foundations"
    weight = 1

[[languages.en.menu.main]]
    parent = "categories"
    name = "Projects"
    url = "categories/projects"
    weight = 2

[[languages.en.menu.main]]
    parent = "categories"
    name = "Success Stories"
    url = "categories/success_stories"
    weight = 3

[[languages.en.menu.main]]
    parent = "categories"
    name = "Utilities"
    url = "categories/utilities"
    weight = 4

[[languages.en.menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[languages.en.menu.main]]
    name = "contact"
    url = "page/contact/"
    weight = 4

[[languages.en.menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5

#[Params]
  #homeTitle = "Datalaria" # Set a different text for the header on the home page
  #subtitle = "Aprendiendo con los datos"
  #logo = "img/datalaria-logo.png"
  #favicon = "img/datalaria-icon.ico"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Datalaria"
  website = "https://datalaria.github.io/"
  email = "datalaria@gmail.com"
  stackoverflow = "users/9717082/datalaria"
  github = "datalaria"
  twitter = "datalaria"
  googleplus = "109028448665903718613" # or xxxxxxxxxxxxxxxxxxxxx
  linkedin = "daniel-aláez-riaño-362257132"

  # facebook = "username"
  # gitlab = "username"
  # bitbucket = "username"
  # reddit = "username"
  # xing = "username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"

# [[taxonomies]]
#     tag = "tags"
#     category = "categories"
